### PR TITLE
fix links to IGES and NASTRAN on Ukrainian translation

### LINKED ISSUE #195: Broken links to IGES and NASTRAN on Ukrainian language
Link: https://www.freecad.org/features.php?lang=uk
Section: "File formats frenzy"

This section on Urkainian language contains HTML code for `<a>` element.

Screenshot of the page with an issue:
Screenshot from 2024-09-20 16-28-29

Same place on the English page version:
image

### PR DESCRIPTION
**Pull request by valerii-zinchenko**
Fix `<a>` element

fix #195

### CODE REVIEW

**Comment by Reqrefusion** [comment]
Hello, great correction, but translation-related corrections are made via [crowdin](https://crowdin.com/project/freecad). I suggest you correct it there.

**Comment by valerii-zinchenko** [comment]
Hi @Reqrefusion! Thanks! I saved there the changes. Sorry I do not know the process, is there is anything else I should do after that? Something like, link those changes with this ticket

**Comment by chennes** [comment]
Once @yorikvanhavre runs a new translation cycle you can just close #195 manually.

**Comment by valerii-zinchenko** [comment]
Ok, got it. Thanks! Canceling this PR.

**Pull request closed without merging**
