### PR TITLE
Website: Add blur effect to navbar

### PR DESCRIPTION
**Pull request by theabhayprajapati**
Improved the Navbar by adding a backdrop which make the background bit of glassy.

### CODE REVIEW

**Comment by theabhayprajapati** [comment]
# Improvement
Notice the Navbar on the top

## With Backdrop
image
## Without Backdrop
image

**Review by luzpaz — APPROVED** [review]

**Comment by luzpaz** [comment]
@yorikvanhavre ping

**Comment by theabhayprajapati** [comment]
hii @luzpaz do we have a discord channel

**Comment by luzpaz** [comment]
https://forum.freecadweb.org/viewtopic.php?f=9&t=60988

**Comment by luzpaz** [comment]
Please rename this issue so we can quickly identify what it's addressing

**Comment by theabhayprajapati** [comment]
Hey Actually I had created this issue for PR which can. improved the Navigation bar by adding blur effect on the background.

**Comment by yorikvanhavre** [comment]
Sorry about the delay guys! Great fix!

**Pull request merged**
