### PR TITLE
Add on header a link to help for translations/localisation

### PR DESCRIPTION
**Pull request by marcuspollio**
Hi !
Here is a small update to header.php to include a wiki link for people interested to help in translations/localisation.
Adding the link to the wiki as the page has more information about translations overall than directly on Crowdin seems appropriate to me. What do you think ?

printscreen

### CODE REVIEW

**Comment by luzpaz** [comment]
Can you provide a screenshot of how this looks like ?

**Comment by marcuspollio** [comment]
Oulà ... !
Looks like the "pre-commit" messed with many files unrelated to my change.
Should I revert anything ?

**Comment by luzpaz** [comment]
CC @kaktusus

**Comment by luzpaz** [comment]
> Oulà ... ! Looks like the "pre-commit" messed with many files unrelated to my change. Should I revert anything ?

I think a dev can cherrypick and merge for you. But it's good to follow the contributor guidelines from here on out (https://freecad.github.io/DevelopersHandbook/gettingstarted/)

**Comment by marcuspollio** [comment]
> follow the contributor guidelines
Yeah, sure ! Will do next time. This change was so small I did the edit directly in GH...

> Edit: and thank you so much for you contribution!
You're welcome. One has to start somewhere... =D

**Comment by luzpaz** [comment]
Edit 2: https://github.com/FreeCAD/FreeCAD-Homepage/pull/134#issuecomment-1738306949

**Comment by marcuspollio** [comment]
> > Can you provide a screenshot of how this looks like ?

Thanks Luzpaz for your support.

I just updated the OP with a screenshot.

As I struggled a bit to find a way to open the php file locally, here is a small hint for anyone looking to open a website folder (FreeCAD Homepage for example) on his web browser without using Apache, XAMPP or others :

1) download the repository (< > Code green button on Github) and unzip
2) make sure php is installed (for me on GNU/Linux, I had to install "php8.1-cli" as of September 2023)
3) go to my local copy of the website folder ("FreeCAD-Homepage-master" in this case)
4) open the terminal and paste `php -S 127.0.0.1:8000`
5) as there is an "index.php" file in the FreeCAD case, opening a new tab in your web browser with `localhost:8000/` displays the web page correctly. If you want to reach a particular file, use `localhost:8000/MyFile.php`

Hope it helps other folks... And sorry for the off-topic XD

**Comment by kaktusus** [comment]
> CC @kaktusus

The idea seems interesting.

The work of a translator for the FreeCAD project can be carried out on two separate levels that are closely intertwined.
I'm thinking here of the GUI and Crowdin, and the documentation and Wiki.
Maybe instead of a single link, it would be worthwhile to prepare a small piece of content that would cover the topic in more detail and explain something.

**Comment by kaktusus** [comment]
@marcuspollio  
I'll ask you to take a look at this thread at your leisure _(it's about code formatting and problems arising for translators)_
https://github.com/FreeCAD/FreeCAD-translations/issues/275

I'm curious if you are a translator. :wink:

**Comment by chennes** [comment]
@marcuspollio are you confident enough in your git skills to rebase to master and drop [9a29325](https://github.com/FreeCAD/FreeCAD-Homepage/pull/134/commits/9a29325ee56b764908fa84298ad168c8f02fdeb7)? It should not longer be needed.

**Comment by marcuspollio** [comment]
Hi @chennes !
Well, as I'm still learning all of this, I'll start again from a fresh repo =D
Coming back later...

**Pull request closed without merging**
