### PR TITLE
#73 navigation spacing error fixed.  

### PR DESCRIPTION
**Pull request by theabhayprajapati**

### CODE REVIEW

**Comment by theabhayprajapati** [comment]
image




**now there is spacing b/w navbar elements**

**Comment by yorikvanhavre** [comment]
I don't see which error this commit fixes? As far as I can see it makes spacing a little bit wider... In any case wouldn't it be better to add this to css instead?

**Comment by theabhayprajapati** [comment]
ok sure I will make the changes in the CSS files

**Comment by theabhayprajapati** [comment]
did this with #113 PR

**Comment by theabhayprajapati** [comment]
image

I made the spacing bit less than the previous PR from 0.5 to 0.25

**Comment by yorikvanhavre** [comment]
Closing this in favor of #113

**Pull request closed without merging**
