### PR TITLE
1.0 is now on the menu

### PR DESCRIPTION
**Pull request by Reqrefusion**
A small addition to the menu to celebrate the release of 1.0. The icon was made by SpeeQz on the discord server. And it is currently used as the icon of the discord server.

resim

### CODE REVIEW

**Comment by SpeeQz1** [comment]
Provided is the SVG used for the logo:

Inkscape-1-0

**Comment by Reqrefusion** [comment]
> Nice!! I liked it :)

@yorikvanhavre Enough to merge or enough to see from afar? :D

**Comment by yorikvanhavre** [comment]
Let's do it at M3 today

**Comment by Reqrefusion** [comment]
> Let's do it at M3 today

@yorikvanhavre PR meetings are so full right now, that's why we're holding them twice a week, right? I don't think anyone will say no to this change. If there is a problem with the relevant picture, we will change it too. But I think it's a very nice looking picture, in the appropriate size and compatible with the logo. I was actually working on something more exaggerated with confetti, but I think this would be the most elegant and pleasant promotion for 1.0.

**Comment by yorikvanhavre** [comment]
Okay let's do it then

**Pull request merged**
