### PR TITLE
Update website to reflect v0.20 release

### PR DESCRIPTION
**Pull request by luzpaz**
A collection of changes that collectively update the freecad.org homepage info to reflect the latest release of v0.20

### CODE REVIEW

**Comment by luzpaz** [comment]
I'd like to also improve download.php per https://github.com/FreeCAD/FreeCAD-Homepage/issues/90

**Comment by luzpaz** [comment]
@donovaly this was missing URLs for the following stable build : Linux, MacOS and windows conda

**Comment by donovaly** [comment]
> URLs for the following stable build

This will be updated when we have these builds. So in about one or two days.

**Comment by luzpaz** [comment]
I originally left it as a Draft PR with that that intention.

**Pull request closed without merging**
