### PR TITLE
Added Error 404 page.

### LINKED ISSUE #121: [Change] Error 404 page
Incorporating a 404 error page featuring the FreeCAD logo, a clear option to return to the home page, and a footer displaying contact details can enhance user experience and simplify navigation on the website. 
 
 Current 404 error page -
 
image
 

I would like to revamp the error 404 page of the website.

### PR DESCRIPTION
**Pull request by AdarshRawat1**
Closes #121 
In the event of a 404 error, a customized error 404 page will be displayed.

Please share your ideas on how to improve the image on the error 404 page [here](https://github.com/FreeCAD/FreeCAD-Homepage/issues/121)

image

### CODE REVIEW

**Comment by chennes** [comment]
I'm not thrilled with the diagrams.net SVG with all the embedded binary data. Can we make something simpler in Inkscape instead?

**Comment by AdarshRawat1** [comment]
Noted ! Will update it .
Any suggestions on what image should be used?

**Comment by yorikvanhavre** [comment]
Honestly I'd either reuse the current image, or use a "error" icon (make sure you use one with an open license). Maybe there is a suitable icon in FreeCAD itself? https://github.com/FreeCAD/FreeCAD/tree/master/src/Gui/Icons

**Comment by AdarshRawat1** [comment]
@yorikvanhavre I will review the existing icons in FreeCAD and select the most suitable one for the error page.

**Comment by AdarshRawat1** [comment]
@chennes @yorikvanhavre  please check the icon.

**Comment by chennes** [comment]
I think this is a good improvement over what we had. If one of our resident graphics designers wants to give it a look later on, more power to them. Thanks for the PR!

**Comment by chennes** [comment]
Oh, but I wasn't thinking about it... we're on nginx, it doesn't use the .htaccess settings.

**Pull request merged**
