### PR TITLE
FreeCAD 0.20 site revamp

### PR DESCRIPTION
**Pull request by yorikvanhavre**
I'd like to propose a reworking of the website to celebrate 0.20 release and the new possibilities that the FPA offers.
Basically the changes here include:

* A refomatted logo and font as per https://github.com/FreeCAD/FPA/issues/8
* A different cover drawing, replacing the rendered gear by a FreeCAD-made gear (.FCStd file included below, requires the gears addon)
* Simplified top menu (removed some "dead" links, added topics under "documentation") and footer (removed links)
* A "Sponsoring/donation" page with one-time and recurring donation forms that redirect to payment platforms, and display of sponsors.
* A "thank you" page that appears after a person clicks on one of the download links with donation options and help

Here are a couple of screenshots:

Screenshot from 2022-06-21 09-43-16
Screenshot from 2022-06-21 09-43-35
Screenshot from 2022-06-21 09-43-50
Screenshot from 2022-06-21 09-43-59
Screenshot from 2022-06-21 09-44-14
Screenshot from 2022-06-21 09-44-22
Screenshot from 2022-06-21 09-44-42
Screenshot from 2022-06-21 09-44-55

The sponsoring page proposes 4 sponsoring tiers:

* Normal sponsor: from 1 USD / 1 EUR per month: No particular privileges
* Bronze sponsor: from 25 USD / 25 EUR per month: Name or company name displayed on the page.
* Silver sponsor: from 100 USD / 100 EUR per month: Name or company name displayed on the page, with a link to website, and a one-line description text.
*Gold sponsor: from 200 USD / 200 EUR per month: Name or company name and logo displayed on the page, with a link to website and a custom description text. Companies that have helped FreeCAD early on also appear under Gold sponsors.

Of course all this should be discussed before implementing and can be tuned afterwards, but I thought best to come up with a ready-to-go solution already ;)

So, how does that sound?

[homepage gears (rename to FCStd).zip](https://github.com/FreeCAD/FreeCAD-Homepage/files/8946931/homepage.gears.rename.to.FCStd.zip)

### CODE REVIEW

**Comment by luzpaz** [comment]
Nice!!!

**Comment by sliptonic** [comment]
How about throwing a toolpath around one of those gears?

**Comment by sliptonic** [comment]
I think that looks good!

**Comment by yorikvanhavre** [comment]
Okay then :) let's unleash

**Comment by MisterMakerNL** [comment]
Since it is serious CAD software it is probably a good idea to make the drawing according to drawing standards.
So some remarks.
Could you add a ∅ symbol to the 29,59 and the 11. (probably best to do with both 29,59, although can debate about the bottom one)
And adding a H7 to the 11mm, but this is just to make it more technical since you don't have too add tolerances to it. Although most gearwheels have probably a H7 on the hole. 

So ends up twice ∅29,59 and ones ∅11H7 (example: https://nadro.nl/mark/img/iso_eenheids-passing.png)
If you want to go more technical you can add module dimension as shown here:
afbeelding
I would make the adjustments myself, but I have absolutely no clue on how to do this. I assume it is the drafts workbench?

**Comment by MisterMakerNL** [comment]
I did it myself used text override and added this: "Ø $dim"
[homepage.gears.rename to fcstd.zip](https://github.com/FreeCAD/FreeCAD-Homepage/files/8970311/homepage.gears.rename.to.fcstd.zip)

**Pull request merged**
