### PR TITLE
Update to 0.18.2 download links

### PR DESCRIPTION
**Pull request by luzpaz**
Updated from `r16110` to `r16117`

CC @sgrogan

### CODE REVIEW

**Comment by luzpaz** [comment]
@kkremitzki ping

**Comment by luzpaz** [comment]
I also fixed the AppImage link on the [FC AppImage wiki page](https://www.freecadweb.org/wiki/Appimage#Stable_version). We need to improve our communication in the context of updating the stable appimages. We know there are 3 places we need to update when a new stable appimage is released:  
1. Linux Condda Appimage per a31ff0e0d3  
2. MacOS Conda dmg per a31ff0e0d3  
3. [FC AppImage wiki page](https://www.freecadweb.org/wiki/Appimage#Stable_version)

CC @looooo

**Comment by sgrogan** [comment]
We'll get there
https://github.com/FreeCAD/FreeCAD/releases/latest
should resolve to
https://github.com/FreeCAD/FreeCAD/releases/tag/0.18.2

The problem with using "latest" is that the link will be broken for the builds that aren't populated. The advantage is that the tar's are up to date.

The problem with the .dmg and AppImage is that they were deployed to 0.18.1 and the older builds were pruned. I can move them, but that will break the builds again.

**Comment by luzpaz** [comment]
@sgrogan can you merge this PR in the meantime ?

**Comment by sgrogan** [comment]
I copied (actually downloaded/uploaded) the packages to the 0.18.2 release.
The win x64 link also needs to be updated. I am working on the win x32 installer.
Also see here: https://forum.freecadweb.org/viewtopic.php?f=21&t=35769#p302539

I think the Home page should point to the latest 0.18.2 Github releases page. I've added to my list why the .dmg's and .AppImage deployed to the wrong place.
I didn't delete the packages on 0.18.1 (that were improperly deployed yet)

I do have merge privileges for this repo surprisingly,  so I can when we agree.

**Comment by luzpaz** [comment]
pushed a new commit to this PR 7a3b9c1  
updates all the download links to 0.18.2 (I've commented out the win32 download button for now until we have that link available)  
FYI https://www.freecadweb.org/tracker/view.php?id=3992

**Comment by looooo** [comment]
sorry for not responding. The automatic appimage/dmg creation will upload the latest 0.18 bundle to a constant upload-adress. So if a 0.18.3 is available I will update the conda-packages and the script in FreeCAD/Appimage uses the latest available 0.18 script. 

I guess it makes most sense to have only one bundle for every release and keep the different builds as conda-packages for testing. So in my eyes it would make more sense to always upload to 0.18 release. If someone is interested in testing difference of 0.18.1 and 0.18.2 he/she can use conda directly. In conda-forge-land no builds get deleted...

So my conclusion is:
Only one bundle for every release / platform (at least for conda-based bundles).

**Comment by luzpaz** [comment]
@sgrogan for now I :+1: to merge this PR. It looks bad when our download links aren't working.

**Comment by luzpaz** [comment]
We also need to update this line in the php when we update minor stable versions

https://github.com/FreeCAD/FreeCAD-Homepage/blob/master/downloads.php#L97

**Comment by sgrogan** [comment]
I merged this.

@looooo You do far to much already. Do what you want and we will adapt.
I need more time to think about this, but maybe, we should consider a release page from the FreeCAD_Conda repo? The whole point release and point release release pages is all to deal with combinations of permutations of combinations of all the distros and packaging systems.

**Pull request merged**
