### PR TITLE
Wrapped CONTRIBUTING and CODE OF CONDUCT

### PR DESCRIPTION
**Pull request by yorikvanhavre**
These two menu links were pointing at corresponding pages on github. With this PR, both github pages are now wrapped and shown with the CSS of this site.

image

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Darn it changed all the files, even the minified ones :)

**Comment by chennes** [comment]
Yeah, I'd exclude *.svg and *.min.js from the run.

**Comment by luzpaz** [comment]
0f412941138db056f7e378690c022bebffea2d88 looks good

**Comment by yorikvanhavre** [comment]
Okay I made it only consider php files for now... we can extend bit by bit later

**Comment by chennes** [comment]
@yorikvanhavre can you rebase and drop 2c71cc7?

**Comment by yorikvanhavre** [comment]
@chennes Dropped the commit, but there is still the commit I did to only consider php files... I think after your recent config changes it's best to drop that one too, right?

**Comment by yorikvanhavre** [comment]
Okay I think this is good now... I let you guys press the button so I don't selfmerge ;)

**Pull request merged**
