### PR TITLE
Correct some accessibility issues

### PR DESCRIPTION
**Pull request by drmenzelit**
PR for issue #212 

- Added an empty alternative text to the language flags and some other decorative images
- Added alternative text to DigitalOcean logo/link
- Added alternative text to FreeCAD logo/h1
- Changed `<div id="main"...` to `<main>`

There are other things that need to be changed, but probably you need to discuss how first in your team:
- Add a h1 to each page (and maintain the correct heading hierarchie h1->h2->h3...)
- Check the color contrast for text and links
- Mark the current language as selected (you see the flag of the current selected language, but there is no information for screenreader users)

### CODE REVIEW

**Comment by Reqrefusion** [comment]
> There are other things that need to be changed, but probably you need to discuss how first in your team:
> 
>     * Add a h1 to each page (and maintain the correct heading hierarchie h1->h2->h3...)
> 
>     * Check the color contrast for text and links
> 
>     * Mark the current language as selected (you see the flag of the current selected language, but there is no information for screenreader users)

I don't see why these things need to be discussed. You can do these as you wish. These are not things that change the appearance beyond recognition. They basically just increase accessibility. However, if you think there is a big change, you can show it in another PR with before and after pictures.

**Review by yorikvanhavre — APPROVED** [review]
These changes look good and are more than welcome! Thanks for taking on that!

Just a question, is adding `alt="" ` doing better than nothing? Couldn't find that info...

About your proposed further changes, of course, please do!! We should definitely aim for state-of-the-art accessibility

**Comment by drmenzelit** [comment]
@yorikvanhavre : https://www.w3.org/WAI/tutorials/images/decision-tree/

**Comment by yorikvanhavre** [comment]
> @yorikvanhavre : https://www.w3.org/WAI/tutorials/images/decision-tree/

Thanks!

**Pull request merged**
