### PR TITLE
Sisyphus Revision: Home Rolling Stone Blog

### PR DESCRIPTION
**Pull request by Reqrefusion**
A new blog page has been created. This page was envisioned as an intermediate place before going to the blog site. In this way, the last ten blogs are displayed with images. If the blog does not contain images, images are given according to the category. I plan to look more or less like this. Maybe some places need to be changed.

In order for the page to load faster, I took the blog posts with javascript. But in order not to encounter a cors error, I created an rss proxy. In the future, blogs in other places can be pulled in the same way.  I also put Bootstrap placeholders

You can look [here](https://cizgivedizi.com/FreeCAD-Homepage/blog.php).
<details>
  <summary>Screenshots</summary>

resim

resim

</details>

### CODE REVIEW

**Comment by Reqrefusion** [comment]
Add Event page blog section

You can look [here](https://cizgivedizi.com/FreeCAD-Homepage/events.php).
<details>
  <summary>Screenshots</summary>

resim

resim

</details>

**Comment by yorikvanhavre** [comment]
Didn't have enough time yesterday, sorry...

@FreeCAD/design-working-group 
@concretedog 
@prokoudine 
You guys want to have a look here?

**Comment by obelisk79** [comment]
I have an issue with the lack of edge definition of the text blocks on the blog page when superimposed against gray parts of the background image. Other than that, everything seems like an improvement.

**Comment by Reqrefusion** [comment]
> I have an issue with the lack of edge definition of the text blocks on the blog page when superimposed against gray parts of the background image. Other than that, everything seems like an improvement.

I don't think there is a solution to this problem with the current background. Developments have already been made in the past according to your requests. I am open to your suggestions.

**Comment by yorikvanhavre** [comment]
Nobody opposed to it, so, merging!

**Pull request merged**
